version: "3"
services:

  plausible_db:
    container_name: plausible_db
    image: postgres:12
    volumes:
      - /portainer/plausible/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=CHANGEME

  plausible_events_db:
    container_name: plausible_events_db
    image: yandex/clickhouse-server:latest
    volumes:
      - /portainer/plausible/event-data:/var/lib/clickhouse
      - /portainer/plausible/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - /portainer/plausible/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  geoip:
    container_name: geoip
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=48 # number in hours // updates every 2 days
      - GEOIPUPDATE_ACCOUNT_ID=CHANGEME
      - GEOIPUPDATE_LICENSE_KEY=CHANGEME
    volumes:
      - /portainer/plausible/geoip:/usr/share/GeoIP
    restart: always

  plausible:
    container_name: plausible
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - geoip
    ports:
      - 8085:8000
    environment:
      - ADMIN_USER_EMAIL=CHANGEME
      - ADMIN_USER_NAME=CHANGEME
      - ADMIN_USER_PWD=CHANGEME
      - BASE_URL=https://example.example.com
      - SECRET_KEY_BASE=CHANGEME
      - DISABLE_REGISTRATION=false # SET TO FALSE AFTER REGISTERING TO STOP FREELOADERS