version: '3'
services:

    adguard:
        container_name: adguard
        image: adguard/adguardhome:latest
        ports:
            - '53:53/tcp'
            - '53:53/udp'
#            - '67:67/udp'           # DHCP
#            - '68:68/udp'           # DHCP
#            - '80:80/tcp'           # DoH panels
#            - '443:443/tcp'         # DoH panels
#            - '443:443/udp'         # DoH panels
            - '3000:3000/tcp'        # DoH panels
#            - '853:853/tcp'         # DNS-over-TLS server
#            - '784:784/udp'         # DNS-over-QUIC server
#            - '853:853/udp'         # DNS-over-QUIC server
#            - '8853:8853/udp'       # DNS-over-QUIC server
#            - '5443:5443/tcp'       # DNSCrypt server
#            - '5443:5443/udp'       # DNSCrypt server
        volumes:
            - '/portainer/adguard/data:/opt/adguardhome/work'
            - '/portainer/adguard/conf:/opt/adguardhome/conf'
        restart: always