version: '3'

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - 8096:8096
    volumes:
      - /portainer/jellyfin/config:/config
      - /portainer/jellyfin/cache:/cache
      - /portainer/jellyfin/media:/media
    restart: always

#  jellyfin-vue:
#    container_name: jellyfin-vue
#    image: ghcr.io/jellyfin/jellyfin-vue:unstable
#    ports:
#      - 8096:80
#    restart: always
# jellyfin-vue is a new experimental front-end. You'll still need the regular jellyfin service running at the same time.