version: '3'
services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /portainer/npm/data:/data
      - /portainer/npm/letsencrypt:/etc/letsencrypt
    restart: always